package constant

const PASSWORD_ERROR = "密码错误"
const ACCOUNT_NOT_FOUND = "账号不存在"
const ACCOUNT_LOCKED = "账号被锁定"
const UNKNOWN_ERROR = "未知错误"
const USER_NOT_LOGIN = "用户未登录"
const CATEGORY_BE_RELATED_BY_SETMEAL = "当前分类关联了套餐,不能删除"
const CATEGORY_BE_RELATED_BY_DISH = "当前分类关联了菜品,不能删除"
const SHOPPING_CART_IS_NULL = "购物车数据为空，不能下单"
const ADDRESS_BOOK_IS_NULL = "用户地址为空，不能下单"
const LOGIN_FAILED = "登录失败"
const UPLOAD_FAILED = "文件上传失败"
const SETMEAL_ENABLE_FAILED = "套餐内包含未启售菜品，无法启售"
const PASSWORD_EDIT_FAILED = "密码修改失败"
const DISH_ON_SALE = "起售中的菜品不能删除"
const SETMEAL_ON_SALE = "起售中的套餐不能删除"
const DISH_BE_RELATED_BY_SETMEAL = "当前菜品关联了套餐,不能删除"
const ORDER_STATUS_ERROR = "订单状态错误"
const ORDER_NOT_FOUND = "订单不存在"
const ALREADY_EXISTS = "已存在"
